---
- name: Fetch installed RPM packages
  hosts: all
  become: true

  tasks:
    - name: Get list of installed RPM packages
      yum:
        list: installed
      register: rpm_packages

    - name: Create CSV file of RPM packages
      shell: |
        cd /var/www/html/
        rpm -qa > rpm_package_list.csv

    - name: Create HTTP path to CSV file
      set_fact:
        http_path: "http://{{ ansible_default_ipv4.address }}/rpm_packages.csv"

    - name: Display HTTP path to CSV file
      debug:
        var: http_path
